### ISSUE TITLE
Universal app run in browser and renderer process.

### ISSUE THREAD

**Issue by linonetwo** [cdaringe/electron-renderer-react-scripts-target#3]
Can I still keep a version that can still run in the browser?

I create an app via create-react-app, and in Electron, I load it to a renderer process. Your package helped me about that.
But I want my app to be universal, that it could still run in the browser. Can I achieve that?

**Comment by linonetwo** [comment]
I add 
```js
  delete config.node
  config.target = 'electron-renderer';
```
to ```config-overrides.js``` of react-app-rewired, now I can run ```cross-env BROWSER=none react-app-rewired start``` for electron, and ```react-scripts start``` for browser!

**Comment by cdaringe** [comment]
Ah, good call.  Maybe should make that configurable via the env!

**Comment by linonetwo** [comment]
Sure, since in electron I won't let browser open, now I can detect it by ```if (process.env.BROWSER === 'none')``` :P

https://github.com/facebook/create-react-app/issues/3575#issuecomment-362781634
